export default {

    addDocumentButton : 'div[class^="content-area"] div[class^=flex-horizontal] button[class*="btn btn-primary"] > clr-icon[shape="plus-circle"]',
    documentName : 'form[class*="clr-form"] input[name*="docType-name"]',
    documentDescription : 'form[class*="clr-form"]  textarea[name="docType-description"]',
    documentLinkedClassifications : 'form[class*="clr-form"]  input[name="default-classification-search-text"]',
    documentClassificationName : 'div[class="classifications-list"]  span[class*="classification-name"]',
    selectedClassification : 'div[class="classification selected-classification"]',
    thoughtExtraction : 'div[class="clr-control-container"] select[name*="docType-Ontology"] option[class="ng-star-inserted"]',
    oglthoughtExtraction : 'div[class="clr-control-container"] select[name*="docType-Ontology"] option[class="ng-star-inserted"]:nth-of-type(6)',
    documentIcon : "header div .nav-icon clr-icon[shape='tt-logo']",
    listItems : "div[class='clr-control-container'] select[name*='docType-Ontology']",
    documentMenuItem: 'clr-dropdown-menu a[href="/qa/admin/document-types"]',
    tagMenuItem: 'clr-dropdown-menu a[href="/qa/admin/tags"]' , 
    settingsIcon : 'clr-dropdown.no-caret.dropdown.ng-star-inserted > button > clr-icon',
    DocumentModal : '//h3[contains(text(),"New Document Type")]',
    SaveButton : 'div.modal-footer > button.btn.btn-primary',
    documentSearch : 'div > ttc-document-type-management > ttc-search-input > input',
    SearchResultElement : 'div.datagrid-row-scrollable > div > clr-dg-cell.datagrid-cell.ng-star-inserted:nth-child(8) span',
    documentsPageIcon : 'header[class="header header-white"] span[class="nav-text"]',
    expandDocumentIcon : 'div > clr-dg-cell.document-search-actions-column.flex-vertical.datagrid-fixed-width.datagrid-cell.ng-star-inserted > div > a',
    tagNameIcon : 'clr-dg-cell[class*="document-search-tag-column"] span[class^="label"]',
    documentType : 'a[class^="document-type"]',
    tagChip : 'header[class^="header"] div[class*="tag-chip"]',
    tagsInputSearch : 'input[placeholder="Search tags"]',
    tagSelection : 'ul li[title="', // tag_name_previous"]
    tagsFormApplyButton : 'form[class^="filter"]',
    contentSearch : 'input[placeholder="Search"]',
    contentFactTag : 'label[for="content-panel-choice-facts"]',
    factTag : 'div[class="fact-type-name"] div'
};